Repository devRaspberry/hacktoberfest, pull requests merged in 2020-10, with the labels that each got.

#1 Create LICENSE
  LICENSE
Labels: documentation, hacktoberfest-accepted

#2 SwiftHelloWorld
  HelloWorld/HelloWorld..swift
Labels: hacktoberfest-accepted

#3 Flutter hello world
  HelloWorld/HelloWorld.dart
Labels: hacktoberfest-accepted

#4 Hacktober fest Pulll
  HelloWorld/HelloWorld.cpp
  contributors-list.md
Labels: hacktoberfest-accepted

#7 cppProject
  cppProjects/PointerInCPP.cpp
Labels: hacktoberfest-accepted

#8 Implementation of stack and linked list
  linkedList/linkedList.c
  stack/stack.c.c
Labels: hacktoberfest-accepted

#10 Added a Code snippet in Python
  HelloWorld/HelloWorld.py
Labels: hacktoberfest-accepted

#6 🎶 Soundcloud-App
  Soundcloud-App/.gitignore
  Soundcloud-App/README.md
  Soundcloud-App/config/env.js
  Soundcloud-App/config/jest/cssTransform.js
  Soundcloud-App/config/jest/fileTransform.js
  Soundcloud-App/config/modules.js
  Soundcloud-App/config/paths.js
  Soundcloud-App/config/pnpTs.js
  Soundcloud-App/config/webpack.config.js
  Soundcloud-App/config/webpackDevServer.config.js
  Soundcloud-App/package-lock.json
  Soundcloud-App/package.json
  Soundcloud-App/public/favicon.ico
  Soundcloud-App/public/index.html
  Soundcloud-App/public/manifest.json
  Soundcloud-App/scripts/build.js
  Soundcloud-App/scripts/start.js
  Soundcloud-App/scripts/test.js
  Soundcloud-App/src/components/App.js
  Soundcloud-App/src/components/Controls/Controls.js
  Soundcloud-App/src/components/Player/Player.js
  Soundcloud-App/src/components/RecentSearches/RecentSearches.js
  Soundcloud-App/src/components/SearchForm/SearchForm.js
  Soundcloud-App/src/components/Song/SongGrid.js
  Soundcloud-App/src/components/Song/SongList.js
  Soundcloud-App/src/components/SongsGrid/SongsGrid.js
  Soundcloud-App/src/components/SongsList/SongsList.js
  Soundcloud-App/src/index.js
  Soundcloud-App/src/indx.css
  Soundcloud-App/src/styles/Col.js
  Soundcloud-App/src/styles/Container.js
  Soundcloud-App/src/styles/ControlsWrapper.js
  Soundcloud-App/src/styles/PlayerStyle.js
  Soundcloud-App/src/styles/SongGridStyle.js
  Soundcloud-App/src/styles/SongListStyle.js
  Soundcloud-App/src/styles/SongsGridStyle.js
  Soundcloud-App/src/styles/SongsListStyle.js
  Soundcloud-App/yarn.lock
  contributors-list.md
Labels: hacktoberfest-accepted

#11 Changed contributors-list.md, added buttons.css
  contributors-list.md
  css_stuff/buttons.css
Labels: hacktoberfest-accepted

#12 Added typography.css
  css_stuff/typography.css
Labels: hacktoberfest-accepted

#13 Added progressbar.css
  css_stuff/coffee.css
  css_stuff/progressbar.css
Labels: hacktoberfest-accepted

#14 Added spinner.css
  css_stuff/spinner.css
Labels: hacktoberfest-accepted

#15 Chat_syatem_for_multi_thread_Environment
  Chat_system_in_cpp/TCP_client
  Chat_system_in_cpp/TCP_client.c
  Chat_system_in_cpp/server_file/a.out
  Chat_system_in_cpp/server_file/server
  Chat_system_in_cpp/server_file/server.c
  contributors-list.md
Labels: hacktoberfest-accepted

#16 Added hello_contrib_react app
  contributors-list.md
  hello_contribs_react/.gitignore
  hello_contribs_react/README.md
  hello_contribs_react/package-lock.json
  hello_contribs_react/package.json
  hello_contribs_react/public/favicon.ico
  hello_contribs_react/public/index.html
  hello_contribs_react/public/logo192.png
  hello_contribs_react/public/logo512.png
  hello_contribs_react/public/manifest.json
  hello_contribs_react/public/robots.txt
  hello_contribs_react/src/MarkdownViewer.js
  hello_contribs_react/src/index.js
Labels: hacktoberfest-accepted

#17 Add Hello World using PHP
  HelloWorld/HelloWorld.php
  contributors-list.md
Labels: hacktoberfest-processing

#19 Adds lagrange interpolation method in Python
  Lagrange_method/lagrange.py
  contributors-list.md
Labels: hacktoberfest-processing

#20 Create HelloWorld.cs
  HelloWorld/HelloWorld.cs
Labels: hacktoberfest-processing

#21 Create sum of each node in reverse order
  linkedList/sum_of_each_node_in_reverse_order.py
Labels: hacktoberfest-processing

#23 HelloWorld in Perl
  HelloWorld/HelloWorld.pl
Labels: hacktoberfest-accepted

#26 add __name__ == __main__
  HelloWorld/HelloWorld.py
Labels: hacktoberfest-processing

#27 simple chat-bot added
  chat-bot/mail.html
  chat-bot/src.js
Labels: hacktoberfest-processing

#28 Added Fizzbuzz directory and fizzbuzz.py
  FizzBuzz/fizzbuzz.py
Labels: hacktoberfest-accepted

#29 Create pull_request_template.md
  .github/pull_request_template.md
Labels: documentation, enhancement, hacktoberfest-accepted

#30 hacktoberfest
  landingPageWithNav/assets/Ashok_chakra.jpg
  landingPageWithNav/assets/Banner.png
  landingPageWithNav/assets/Make-In-India-1.jpg
  landingPageWithNav/assets/My Post.png
  landingPageWithNav/assets/border
  landingPageWithNav/assets/da9be003b1245f06a7571307600eaacc.png
  landingPageWithNav/assets/footer-logo.png
  landingPageWithNav/assets/footer-logo1.jpg
  landingPageWithNav/assets/hero.jpg
  landingPageWithNav/assets/images.jpg
  landingPageWithNav/assets/outlet.jpg
  landingPageWithNav/assets/page2.jpg
  landingPageWithNav/assets/toggle.svg
  landingPageWithNav/index.html
  landingPageWithNav/main.js
  landingPageWithNav/style.css
Labels: hacktoberfest-accepted

#31 Hacktoberfest C
  cProjects/sum.c
Labels: hacktoberfest-accepted

#32 Add files via upload
  cProjects/asum.c
Labels: hacktoberfest-accepted

#34 Create HelloWorld.rs
  HelloWorld/HelloWorld.rs
Labels: hacktoberfest-accepted

#35 Add files via upload
  HelloWorld/hello.py
Labels: hacktoberfest-processing

#36 Add files via upload
  PytonProjects/Part1_Numbers.py
Labels: hacktoberfest-accepted

#37 Add files via upload
  PytonProjects/Part3_Lists.py
Labels: hacktoberfest-accepted

#38 Add files via upload
  PytonProjects/Part10_Simple_Game.py
Labels: hacktoberfest-accepted
